#!/bin/bash

###############################################################
#./mkPageRepresentations is a script which takes lemmatised web
# pages and builds bag-of-words (BOW) representations for them,
# one BOW per sentence. In the future, more representations 
# be added.
# ./mkPageRepresentations is called by ./mkDomainPages
##############################################################



#Create directory for page representations
mkdir domains/$1-pagereps/

#Iterate through all lemmatised files
for file in domains/$1-lemmas/*
do
	cat $file|sed '1d' > domains/$1.reps.tmp
	#Get page name
	p=`echo $file|sed "s/.*\///"`
	#Get page URL
	url=`cat $file|head -1|sed "s/\#\#\# //"`

	#Write file info
	echo "<page>" > domains/$1-pagereps/$p
	echo -e "\t<url=$url/>" >> domains/$1-pagereps/$p
	echo -e "\t<sentences>" >> domains/$1-pagereps/$p

	#Initialise sentence counter
	sc=0

	#Get bag-of-words representation
	while read l
	do
		sc=`expr $sc + 1` 	#increment sentence counter
		l2=`echo $l|sed "s/\(_.\)[^ ]*/\1/g"`	#only keep first letter of POS tag
		echo -e "\t\t<sentence id=$sc>"
		echo -e "\t\t<BOW>$l2</BOW>"	#print bag-of-words representation
		echo -e "\t\t</sentence>"
	done < domains/$1.reps.tmp  >> domains/$1-pagereps/$p
	echo -e "\t</sentences>" >> domains/$1-pagereps/$p
	echo "</page>" >> domains/$1-pagereps/$p
done

rm -f domains/$1.reps.tmp

